#This file was originally generated by NovalIDE's unitest wizard
import unittest
import noval.util.strutils as strutils
import sys
sys.path.append(r'G:\work\project\Noval\plugins\WebBrowser')

from bs4 import BeautifulSoup,Tag

a = '{0}{1}{0}'.format('1','2')
print (a)

content_code = '''
<div class="monaco-workbench windows">
    <div class="welcomePageContainer">
        <div class="welcomePage">
            <div class="row">
                <div class="splash">
                    <div class="section start">
                        <h2 class="caption">{0}</h2>
                        <ul>
                            <li><a href="#" onclick="NewProject()">{1}</a></li>
                            <li class="windows-only linux-only"><a href="#" onclick="OpenProject()">{2}</a></li>
                        </ul>
                    </div>
                    <div class="section recent">
                        <h2 class="caption">{3}</h2>
                        <p class="none detail">{4}</p>
                    </div>
                    <div class="section help">
                        <h2 class="caption">Help</h2>
                        <ul>
                            <li class="keybindingsReferenceLink"><a href="command:workbench.action.keybindingsReference">Printable keyboard cheatsheet</a></li>
                            <li><a href="command:workbench.action.openIntroductoryVideosUrl">Introductory videos</a></li>
                            <li><a href="command:workbench.action.openTipsAndTricksUrl">Tips and Tricks</a></li>
                            <li><a href="command:workbench.action.openDocumentationUrl">Product documentation</a></li>
                            <li><a href="https://github.com/Microsoft/vscode">GitHub repository</a></li>
                            <li><a href="http://stackoverflow.com/questions/tagged/vscode?sort=votes&pageSize=50">Stack Overflow</a></li>
                            <li><a href="command:workbench.action.openNewsletterSignupUrl">Join our Newsletter</a></li>
                        </ul>
                    </div>
                    <p class="showOnStartup"><input type="checkbox" id="showOnStartup" class="checkbox"> <label class="caption" for="showOnStartup">Show welcome page on startup</label></p>
                </div>
                <div class="commands">
                    <div class="section customize">
                        <h2 class="caption">Customize</h2>
                        <div class="list">
                            <div class="item showLanguageExtensions"><button role="group" data-href="command:workbench.extensions.action.showLanguageExtensions"><h3 class="caption">Tools and languages</h3> <span class="detail">Install support for {0} and {1}
            .replace('{0}', `<span class="extensionPackList"></span>`)
            .replace('{1}', `<a href="command:workbench.extensions.action.showLanguageExtensions" title="Show more language extensions">more</a>`)
                            </span></button></div>
                            <div class="item showRecommendedKeymapExtensions"><button role="group" data-href="command:workbench.extensions.action.showRecommendedKeymapExtensions"><h3 class="caption">Settings and keybindings</h3> <span class="detail">(localize('welcomePage.installKeymapExtension', "Install the settings and keyboard shortcuts of {0} and {1}"))
            .replace('{0}', `<span class="keymapList"></span>`)
            .replace('{1}', `<a href="command:workbench.extensions.action.showRecommendedKeymapExtensions" title="('welcomePage.showKeymapExtensions', "Show other keymap extensions")">(localize('welcomePage.others', "others"))</a>`)
                            </span></button></div>
                            <div class="item selectTheme"><button data-href="command:workbench.action.selectTheme"><h3 class="caption">Color theme</h3> <span class="detail">(localize('welcomePage.colorThemeDescription', "Make the editor and your code look the way you love"))</span></button></div>
                        </div>
                    </div>
                    <div class="section learn">
                        <h2 class="caption">Learn</h2>
                        <div class="list">
                            <div class="item showCommands"><button data-href="command:workbench.action.showCommands"><h3 class="caption">Find and run all commands</h3> <span class="detail">(localize('welcomePage.showCommandsDescription', "Rapidly access and search commands from the Command Palette ({0})")).replace('{0}', '<span class="shortcut" data-command="workbench.action.showCommands"></span>')</span></button></div>
                            <div class="item showInterfaceOverview"><button data-href="command:workbench.action.showInterfaceOverview"><h3 class="caption">Interface overview</h3> <span class="detail">(localize('welcomePage.interfaceOverviewDescription', "Get a visual overlay highlighting the major components of the UI"))</span></button></div>
                            <div class="item showInteractivePlayground"><button data-href="command:workbench.action.showInteractivePlayground"><h3 class="caption">Interactive playground</h3> <span class="detail">(localize('welcomePage.interactivePlaygroundDescription', "Try out essential editor features in a short walkthrough"))</span></button></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
'''.format('Start','New project','Open project...','Recent','No recent projects')

##print (content_code)

sp = BeautifulSoup(content_code, 'html.parser')

t = 'welcomePage emptyRecent'
#print (dir(sp.div))
p = sp.div.find(class_="welcomePage")
print (type(p),dir(p))
print (type(p.attrs),p.attrs['class'],"==============")
p.attrs['class'] = t

li = Tag(name='li')
img = Tag(name='img',attrs={'src':'http://www.novalide.com/media/images/project.png'})
a = Tag(name='a',attrs={'href':'command:workbench.action.selectTheme'})
a.string = 'gggg'
a.insert(0,img)
li.append(a)
print (li)


p1 = sp.div.find(class_="section recent")
p1.insert(1,li)

print (p1,"----------------")
#.replace_with(t)
#for child in sp.div.children:
  #  print (child,type(child))
# replace the paragraph using `replace_with` method
#sp.find(class='welcomePage').replace_with(t)

print (sp.prettify())


class TestGlobalFunction(unittest.TestCase):
    def setUp(self):
        pass
    def tearDown(self):
        pass

    def testparseArgs(self):
        pass
        #print strutils.parseArgs('((diamond-run-1.0,/usr/share/gtxcloud/sh/gtxcloud-lite-common.sh,database),/home/wukan/gtx_wgs/dags/wukan/gtxcloud/test_pipline/run0001/gtxcloud-worker-1.1.3dev-x86_64_ubuntu_16.tar.gz,--dir s3://wukan_C41_HNHHLCCXX_L6_run)')


if __name__ == "__main__":
    unittest.main()
