#This file was originally generated by NovalIDE's unitest wizard
import unittest
import os
import noval.util.utils as utils
import sys
parser_path = os.path.join(utils.get_app_path(),"noval","python","parser")
print (parser_path)
sys.path.append(parser_path)
import noval.python.parser.fileparser as fileparser
import pickle
import json

class TestGlobalFunction(unittest.TestCase):
    def setUp(self):
        pass
    def tearDown(self):
        pass

    def testdump(self):
        file_parser = fileparser.FiledumpParser("G:\\work\\project\\Noval\\noval\\python\\debugger\\debuggerharness.py","./",force_update=True)
        file_parser.Dump()
        with open(file_parser.member_file_path,'rb') as f:
            datas = pickle.load(f)
        print (json.dumps(datas,indent=4))

    def testrun(self):
        os.system(r"python G:\work\project\Noval\noval\python\parser\run.py ./tests 1.1.1")
        os.system(r"C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\python.exe G:\work\project\Noval\noval\python\parser\run.py ./tests 1.1.1")



if __name__ == "__main__":
    unittest.main()
