#This file was originally generated by NovalIDE's unitest wizard
import unittest
import noval.util.strutils as strutils

class TestGlobalFunction(unittest.TestCase):
    def setUp(self):
        pass
    def tearDown(self):
        pass

    def testparseArgs(self):
        print strutils.parseArgs('((diamond-run-1.0,/usr/share/gtxcloud/sh/gtxcloud-lite-common.sh,database),/home/wukan/gtx_wgs/dags/wukan/gtxcloud/test_pipline/run0001/gtxcloud-worker-1.1.3dev-x86_64_ubuntu_16.tar.gz,--dir s3://wukan_C41_HNHHLCCXX_L6_run)')


if __name__ == "__main__":
    unittest.main()
