#This file was originally generated by NovalIDE's unitest wizard
import sys
import os
import unittest
import noval.util.utils as utils
parser_path = os.path.join(utils.get_app_path(),"noval","python","parser")
sys.path.append(parser_path)
import noval.python.parser.codeparser as codeparser

class TestCodeParser(unittest.TestCase):
    def setUp(self):
        self._code_parser = codeparser.CodeParser()


    def tearDown(self):
        pass

    def testStop(self):
        pass

    def testParse(self):
        pass

    def testParseContentPY2(self):
        pass

    def testParseContentPY3(self):
        filepath = r"C:\Python27\Lib\site-packages\wx-3.0-msw\wx\_core.py"
        print (self._code_parser.Parsefile(filepath),"=============")

if __name__ == "__main__":
    unittest.main()
