#This file was originally generated by NovalIDE's unitest wizard
from __future__ import print_function
import unittest
import noval.util.utils as utils

class TestRegistry(unittest.TestCase):
    def setUp(self):
        self.config = utils.Config("NovalIDE")
    def tearDown(self):
        pass

    def test__init__(self):
        pass

    def testGroups(self):
        names = []
        self.config.GetGroups("NOV_Projects/{C30979CF-3D7B-11E8-ACDF-60EB694D72B8}/NovalIDE.py/",names)
        print (names,"..............")
        

    def testDeleteEntry(self):
        self.config.DeleteEntry("NOV_Projects/{C30979CF-3D7B-11E8-ACDF-60EB694D72B8}/NovalIDE.py/Noval NovalIDE.py/Arguments/InterpreterOptions")
        

    def testDeleteGroup(self):
        self.config.DeleteGroup("NOV_Projects/{C30979CF-3D7B-11E8-ACDF-60EB694D72B8}/NovalIDE.py")
        self.config.DeleteGroup("NOV_Projects/{1C1B42D1-0B3D-11E9-A584-005056C00008}/NovalIDE.py")
        self.config.DeleteGroup("NOV_Projects/{1C1B42D1-0B3D-11E9-A584-005056C00008}/thonny|__main__.py")

if __name__ == "__main__":
    unittest.main()
