#This file was originally generated by NovalIDE's unitest wizard
import unittest
import noval.util.strutils as strutils
import wx

class TestGlobalFunction(unittest.TestCase):
    def setUp(self):
        pass
    def tearDown(self):
        pass

    def testRGBToHex(self):
        print strutils.RGBToHex(wx.Colour(0,0,0))
        print strutils.RGBToHex(wx.Colour(0xFF,0xFF,0xFF))
        print strutils.RGBToHex(wx.Colour(240,240,250))


if __name__ == "__main__":
    unittest.main()
